In [ ]:
import pandas as pd
import pylab
import matplotlib.pyplot as plt

%pylab inline

In [21]:
import glob
csvs = glob.glob("data/*.csv")

dfs = [pd.read_csv(csv) for csv in csvs]
for df in dfs:
    df['@MeasurementDateGMT'] = pd.to_datetime(df['@MeasurementDateGMT'], format="%Y-%m-%d %H:%M:%S")
dfs = [df.set_index("@MeasurementDateGMT") for df in dfs]

In [57]:
filtered_dfs = [df for df in dfs if 'NO2' in df['@SpeciesCode'].unique()]
len(filtered_dfs)
big_df = pd.concat(filtered_dfs)
big_df_filtered = big_df[big_df['@SpeciesCode'] == "NO2"]

In [27]:
from collections import Counter
Counter([len(df['@SpeciesCode'].unique()) for df in dfs])

Counter({1: 22, 2: 35, 3: 22, 4: 14, 5: 8, 6: 3, 7: 1})

In [52]:
site_means = [(df['@SiteCode'].iloc[0], df[df['@SpeciesCode'] == 'NO2']['@Value'].dropna().mean()) for df in filtered_dfs]
import math
site_means = [s for s in site_means if not math.isnan(s[1])]

In [54]:
sorted(site_means, key=lambda x: x[1], reverse=True)

[('CT6', 96.596734442390641),
 ('LB4', 93.614516129032268),
 ('NB1', 93.600274473924969),
 ('CD9', 85.114070252034139),
 ('IM1', 81.919970507689058),
 ('CT4', 81.836998011928429),
 ('KC5', 77.825549613784901),
 ('MY1', 76.720027899561572),
 ('WM6', 74.69407333994053),
 ('HF4', 74.056085395051866),
 ('EA6', 73.388775305672482),
 ('BT4', 72.355448430493283),
 ('WA7', 69.394439879485063),
 ('KC3', 68.304880976195236),
 ('LB5', 66.012295735352737),
 ('KC4', 64.890664236532999),
 ('WA8', 63.908722024681026),
 ('GR8', 62.498485191046797),
 ('HI0', 55.361003172085653),
 ('TH4', 55.03516064257029),
 ('HK6', 55.021068427370956),
 ('WAB', 54.529261622607102),
 ('LW4', 54.189431054919012),
 ('ST4', 52.798259734609523),
 ('KC2', 52.128007327498473),
 ('CD1', 51.446234641300038),
 ('ST6', 50.715676959619948),
 ('KT4', 49.381583519483748),
 ('CR9', 47.621534506624478),
 ('EI1', 46.611126113961653),
 ('IS2', 46.503287356321835),
 ('LW2', 45.836090882609959),
 ('SK5', 45.609242695289211),
 ('BT5', 45.393310566492566),
 ('EN5', 44.935864182975713),
 ('CR5', 44.44999010488818),
 ('EA8', 44.148756756756754),
 ('BT6', 43.572642998027618),
 ('GN4', 42.958161616161618),
 ('GB6', 42.495050525881624),
 ('HR2', 42.180663751987275),
 ('HV3', 42.159034555526254),
 ('LW1', 41.59005917159763),
 ('WM0', 41.36222535779077),
 ('TH2', 41.021648044692739),
 ('BL0', 40.2352403655145),
 ('GR7', 40.116097849674489),
 ('GR9', 39.380663093110975),
 ('CT3', 38.8643924101736),
 ('RB4', 37.930809610337164),
 ('WA2', 36.220607974733518),
 ('GN0', 36.148912183544311),
 ('HG1', 36.077217941118356),
 ('EN4', 36.049891239865531),
 ('WA9', 33.94407074514352),
 ('GN3', 33.943211120064461),
 ('SK6', 33.821687226422597),
 ('HV1', 33.25929956470123),
 ('RI1', 32.290519454868651),
 ('HR1', 32.160379384395135),
 ('IS6', 31.497002954833267),
 ('ST5', 30.869109424920129),
 ('BG2', 30.636154696132596),
 ('KC1', 30.351426307448495),
 ('WAA', 30.123901581722318),
 ('RB7', 29.618886246531911),
 ('CR7', 28.720268934150681),
 ('BX2', 28.209383268878486),
 ('EN1', 25.864164361912287),
 ('LB6', 25.815043496711226),
 ('ST8', 24.222118380062309),
 ('BX1', 23.184527584020291),
 ('HG4', 22.859644619940767),
 ('BG1', 22.574302496328929),
 ('EN7', 21.337457660888624),
 ('RI2', 21.200611681136543),
 ('GR4', 20.566270313119301),
 ('BQ7', 20.281299172886825)]

In [51]:
q.dropna()['@Value'].mean()

nan

                     Unnamed: 0 @SpeciesCode  @Value @SiteCode
@MeasurementDateGMT
2017-01-01 12:00:00           0          NO2    96.5       WA8
2017-01-01 13:00:00           1          NO2   101.5       WA8
2017-01-01 14:00:00           2          NO2    74.6       WA8
2017-01-01 15:00:00           3          NO2    66.2       WA8
2017-01-01 16:00:00           4          NO2    73.0       WA8
2017-01-01 17:00:00           5          NO2    71.3       WA8
2017-01-01 18:00:00           6          NO2    70.6       WA8
2017-01-01 19:00:00           7          NO2    79.3       WA8
2017-01-01 20:00:00           8          NO2    69.2       WA8
2017-01-01 21:00:00           9          NO2    57.0       WA8
2017-01-01 22:00:00          10          NO2    52.8       WA8
2017-01-01 23:00:00          11          NO2    61.3       WA8
2017-01-02 00:00:00          12          NO2    37.1       WA8
2017-01-02 01:00:00          13          NO2    24.7       WA8
2017-01-02 02:00:00          14          NO2    18.7       WA8
2017-01-02 03:00:00          15          NO2    18.2       WA8
2017-01-02 04:00:00          16          NO2    25.2       WA8
2017-01-02 05:00:00          17          NO2    50.7       WA8
2017-01-02 06:00:00          18          NO2    47.8       WA8
2017-01-02 07:00:00          19          NO2    57.7       WA8
2017-01-02 08:00:00          20          NO2    55.2       WA8
2017-01-02 09:00:00          21          NO2    70.8       WA8
2017-01-02 10:00:00          22          NO2   102.0       WA8
2017-01-02 11:00:00          23          NO2    92.0       WA8
2017-01-02 12:00:00          24          NO2   119.9       WA8
2017-01-02 13:00:00          25          NO2   110.7       WA8
2017-01-02 14:00:00          26          NO2    95.7       WA8
2017-01-02 15:00:00          27          NO2    96.6       WA8
2017-01-02 16:00:00          28          NO2   132.7       WA8
2017-01-02 17:00:00          29          NO2   210.7       WA8
...                         ...          ...     ...       ...
2017-07-31 06:00:00       10146         PM10    26.0       ST8
2017-07-31 07:00:00       10147         PM10    25.0       ST8
2017-07-31 08:00:00       10148         PM10    20.0       ST8
2017-07-31 09:00:00       10149         PM10    21.0       ST8
2017-07-31 10:00:00       10150         PM10     8.0       ST8
2017-07-31 11:00:00       10151         PM10    16.0       ST8
2017-07-31 12:00:00       10152         PM10     5.0       ST8
2017-07-31 13:00:00       10153         PM10    15.0       ST8
2017-07-31 14:00:00       10154         PM10    15.0       ST8
2017-07-31 15:00:00       10155         PM10    12.0       ST8
2017-07-31 16:00:00       10156         PM10    14.0       ST8
2017-07-31 17:00:00       10157         PM10    16.0       ST8
2017-07-31 18:00:00       10158         PM10    20.0       ST8
2017-07-31 19:00:00       10159         PM10    23.0       ST8
2017-07-31 20:00:00       10160         PM10    29.0       ST8
2017-07-31 21:00:00       10161         PM10    23.0       ST8
2017-07-31 22:00:00       10162         PM10    23.0       ST8
2017-07-31 23:00:00       10163         PM10    23.0       ST8
2017-08-01 00:00:00       10164         PM10     NaN       ST8
2017-08-01 01:00:00       10165         PM10     NaN       ST8
2017-08-01 02:00:00       10166         PM10     NaN       ST8
2017-08-01 03:00:00       10167         PM10     NaN       ST8
2017-08-01 04:00:00       10168         PM10     NaN       ST8
2017-08-01 05:00:00       10169         PM10     NaN       ST8
2017-08-01 06:00:00       10170         PM10     NaN       ST8
2017-08-01 07:00:00       10171         PM10     NaN       ST8
2017-08-01 08:00:00       10172         PM10     NaN       ST8
2017-08-01 09:00:00       10173         PM10     NaN       ST8
2017-08-01 10:00:00       10174         PM10     NaN       ST8
2017-08-01 11:00:00       10175         PM10     NaN       ST8

[1333056 rows x 4 columns]